@startuml

title __MODELS's Class Diagram__\n

  namespace com.example.cbsd_project {
    namespace models {
      class com.example.cbsd_project.models.Message {
          {static} + firebasePath : String
          - content : String
          - messageType : String
          - messageViewType : String
          - sender : String
          + Message()
          + Message()
          + getContent()
          + getMessageType()
          + getMessageViewType()
          + getSender()
          + setContent()
          + setMessageType()
          + setMessageViewType()
          + setSender()
      }
    }
  }
  

  namespace com.example.cbsd_project {
    namespace models {
      class com.example.cbsd_project.models.Participant {
          {static} + firebaseCountName : String
          {static} + firebasePath : String
          - nickname : String
          - participantType : String
          - userID : String
          + Participant()
          + Participant()
          + getNickname()
          + getParticipantType()
          + getUserID()
          + setNickname()
          + setParticipantType()
          + setUserID()
      }
    }
  }
  

  namespace com.example.cbsd_project {
    namespace models {
      class com.example.cbsd_project.models.PinnedMessage {
          {static} + firebaseCountName : String
          {static} + firebasePath : String
          - messageID : String
          + PinnedMessage()
          + PinnedMessage()
          + getMessageID()
          + setMessageID()
      }
    }
  }
  

  namespace com.example.cbsd_project {
    namespace models {
      class com.example.cbsd_project.models.Room {
          {static} + firebasePath : String
          {static} - currentRoom : Room
          - name : String
          - roomID : String
          - roomType : String
          + Room()
          + Room()
          {static} + getCurrentRoom()
          + getName()
          + getRoomID()
          + getRoomType()
          {static} + setCurrentRoom()
          + setName()
          + setRoomID()
          + setRoomType()
      }
    }
  }
  

  namespace com.example.cbsd_project {
    namespace models {
      class com.example.cbsd_project.models.User {
          {static} + firebasePath : String
          {static} - currentUser : User
          - email : String
          - name : String
          - userID : String
          + User()
          + User()
          {static} + getCurrentUser()
          + getEmail()
          + getName()
          + getUserID()
          {static} + setCurrentUser()
          + setEmail()
          + setName()
          + setUserID()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
