@startuml

title __HELPERS's Class Diagram__\n

  namespace com.example.cbsd_project {
    namespace helpers {
      class com.example.cbsd_project.helpers.Constants {
          {static} + MessageLimit : int
          {static} + MessageMenuDelete : int
          {static} + MessageMenuEdit : int
          {static} + MessageMenuPin : int
          {static} + MessageTypeGif : String
          {static} + MessageTypeImage : String
          {static} + MessageTypeLocation : String
          {static} + MessageTypeText : String
          {static} + MessageViewTypeReceiver : String
          {static} + MessageViewTypeSender : String
          {static} + RoomTypePrivate : String
          {static} + RoomTypePublic : String
      }
    }
  }
  

  namespace com.example.cbsd_project {
    namespace helpers {
      class com.example.cbsd_project.helpers.MessagesDBHelper {
          ~ chatDatabase : SQLiteDatabase
          {static} - databaseName : String
          + MessagesDBHelper()
          + getMessages()
          + getPinnedMessages()
          + insertNewMessage()
          + insertNewPinnedMessage()
          + onCreate()
          + onUpgrade()
      }
    }
  }
  

  namespace com.example.cbsd_project {
    namespace helpers {
      class com.example.cbsd_project.helpers.ThemeUtil {
          {static} + CurrentTheme : Theme
          {static} + setCurrentTheme()
          {static} + setTheme()
      }
    }
  }
  

  namespace com.example.cbsd_project {
    namespace helpers {
      enum Theme {
        Blue
        Default
        Green
        Lime
        Red
        label
      }
    }
  }
  

  com.example.cbsd_project.helpers.MessagesDBHelper -up-|> android.database.sqlite.SQLiteOpenHelper
  com.example.cbsd_project.helpers.ThemeUtil +-down- com.example.cbsd_project.helpers.ThemeUtil.Theme


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
